# Generated by Django 4.0.3 on 2022-04-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m7_python', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmuebles',
            old_name='numero_estacionamientos',
            new_name='numero_estac',
        ),
    ]
